# Generated by Django 5.2.14 on 2026-05-11 07:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=50, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('HALFDAY', 'Half Day')], default='PRESENT', max_length=20)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('late_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-check_in'],
                'indexes': [models.Index(fields=['staff', 'date'], name='attendance_staff_i_0601b5_idx'), models.Index(fields=['status'], name='attendance_status_a068a7_idx'), models.Index(fields=['date'], name='attendance_date_d460ba_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
