# Generated by Django 5.2.14 on 2026-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='YasMart Supermarket', max_length=255)),
                ('company_email', models.EmailField(default='info@yasmart.local', max_length=254)),
                ('company_phone', models.CharField(default='+1234567890', max_length=20)),
                ('company_address', models.TextField(default='Main Street, City')),
                ('point_conversion_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Amount required for 1 point', max_digits=10)),
                ('attendance_radius', models.IntegerField(default=50, help_text='Allowed radius in meters for attendance')),
                ('qr_expiry_minutes', models.IntegerField(default=5, help_text='QR code expiry duration in minutes')),
                ('reward_enabled', models.BooleanField(default=True)),
                ('offer_notifications_enabled', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
