# Generated by Django 5.2.14 on 2026-05-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='office_latitude',
            field=models.DecimalField(decimal_places=6, default=10.850383, help_text='Office Latitude', max_digits=9),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='office_longitude',
            field=models.DecimalField(decimal_places=6, default=76.037491, help_text='Office Longitude', max_digits=9),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='attendance_radius',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters for attendance'),
        ),
    ]
