# Generated by Django 5.2.14 on 2026-05-13 06:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transaction_type', models.CharField(choices=[('POINT_ADD', 'Add Points'), ('BALANCE_ADD', 'Add Balance'), ('CONVERT', 'Convert Balance to Points')], db_index=True, max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Reward Transaction',
                'verbose_name_plural': 'Reward Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'transaction_type'], name='rewards_rew_custome_382757_idx'), models.Index(fields=['created_at'], name='rewards_rew_created_b60c6d_idx')],
            },
        ),
    ]
