# Generated by Django 5.2.14 on 2026-05-13 06:16

import apps.customers.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[apps.customers.validators.validate_phone])),
                ('address', models.TextField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0, validators=[apps.customers.validators.validate_non_negative])),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[apps.customers.validators.validate_non_negative])),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('loyalty_id', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-joined_at'],
            },
        ),
    ]
