# Generated by Django 5.2.14 on 2026-06-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage'),
        ),
    ]
